# Generated by Django 4.2.5 on 2023-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_conatact_information_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smedia', models.CharField(max_length=255)),
            ],
        ),
    ]
