# Generated by Django 4.2.5 on 2023-10-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
