# Generated by Django 4.2.5 on 2023-10-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=255)),
                ('tw', models.URLField()),
                ('fb', models.URLField()),
                ('insta', models.URLField()),
                ('dribble', models.URLField()),
                ('ln', models.URLField()),
            ],
        ),
    ]
